class Constants:
    
    FPS = 120
    PIXEL_SIZE = 25
    SCREEN_WIDTH = 400
    SCREEN_HEIGHT = 400
    ENV_HEIGHT = SCREEN_HEIGHT/PIXEL_SIZE
    ENV_WIDTH = SCREEN_WIDTH/PIXEL_SIZE
    NAVIGATION_BAR_HEIGHT = 30